name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:

  call-build-workflow:
    uses: ./.github/workflows/build.yml

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: call-build-workflow
    environment: production

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: go-build

      - name: Copy Files to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.VM_IP }}
          username: ${{ vars.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: app
          target: /home/service_user/service/
          overwrite: true
